import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Contexts
import ContextProvider from "@/contexts/Context.provider";

// Components
import LoadingSpinner from "@/components/state/LoadingSpinner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "BranchBound",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ContextProvider>
          {children}
          <LoadingSpinner />
        </ContextProvider>
      </body>
    </html>
  );
}
