import {
  Geist,
  Geist_Mono,
  Merriweather,
  Inter,
  Oswald,
  Playfair_Display,
} from "next/font/google";
import "./globals.css";

// Contexts
import ContextProvider from "@/contexts/Context.provider";

// Components
import LoadingSpinner from "@/components/state/LoadingSpinner";
import Footer from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Cinematic Design System Fonts
const merriweather = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

export const metadata = {
  title: "BranchBound",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${merriweather.variable} ${inter.variable} ${oswald.variable} ${playfairDisplay.variable} antialiased`}
      >
        <ContextProvider>
          {children}

          <LoadingSpinner />

          <Footer />
        </ContextProvider>
      </body>
    </html>
  );
}
